export const GET_TODOLISTS = 'GET_TODOLISTS'
export const GET_TODOLISTS_SUCCESS = 'GET_TODOLISTS_SUCCESS'
export const GET_TODOLISTS_FAIL = 'GET_TODOLISTS_FAIL'
export const GET_TODOLISTS_LOADING = 'GET_TODOLISTS_LOADING'

export const SAVE_TODOLIST = 'SAVE_TODOLIST'
export const SAVE_TODOLIST_SUCCESS = 'SAVE_TODOLIST_SUCCESS'
export const SAVE_TODOLIST_FAIL = 'SAVE_TODOLIST_FAIL'
export const SAVE_TODOLIST_LOADING = 'SAVE_TODOLIST_LOADING'

export const DELETE_TODOLIST = 'DELETE_TODOLIST'
export const DELETE_TODOLIST_SUCCESS = 'DELETE_TODOLIST_SUCCESS'
export const DELETE_TODOLIST_FAIL = 'DELETE_TODOLIST_FAIL'
export const DELETE_TODOLIST_LOADING = 'DELETE_TODOLIST_LOADING'



export const GET_TODOS_FOR_LIST = 'GET_TODOS_FOR_LIST'
export const GET_TODOS_FOR_LIST_SUCCESS = 'GET_TODOS_FOR_LIST_SUCCESS'
export const GET_TODOS_FOR_LIST_FAIL = 'GET_TODOS_FOR_LIST_FAIL'
export const GET_TODOS_FOR_LIST_LOADING = 'GET_TODOS_FOR_LIST_LOADING'

export const SAVE_TODO = 'SAVE_TODO'
export const SAVE_TODO_SUCCESS = 'SAVE_TODO_SUCCESS'
export const SAVE_TODO_FAIL = 'SAVE_TODO_FAIL'
export const SAVE_TODO_LOADING = 'SAVE_TODO_LOADING'

export const DELETE_TODO = 'DELETE_TODO'
export const DELETE_TODO_SUCCESS = 'DELETE_TODO_SUCCESS'
export const DELETE_TODO_FAIL = 'DELETE_TODO_FAIL'
export const DELETE_TODO_LOADING = 'DELETE_TODO_LOADING'

export const UPDATE_TODO = 'UPDATE_TODO'
export const UPDATE_TODO_SUCCESS = 'UPDATE_TODO_SUCCESS'
export const UPDATE_TODO_FAIL = 'UPDATE_TODO_FAIL'
export const UPDATE_TODO_LOADING = 'UPDATE_TODO_LOADING'

export const CLEAR_TODOS_FOR_LIST = 'CLEAR_TODOS_FOR_LIST'

export const LOGIN_USER = 'LOGIN_USER'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL'
export const LOGIN_USER_LOADING = 'LOGIN_USER_LOADING'

export const LOG_OUT = 'LOG_OUT'
export const LOG_OUT_SUCCESS = 'LOG_OUT_SUCCESS'
export const CLEAR_USER = 'CLEAR_USER'

export const REGISTER_USER = 'REGISTER_USER'
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'
export const REGISTER_USER_FAIL = 'REGISTER_USER_FAIL'
export const REGISTER_USER_LOADING = 'REGISTER_USER_LOADING'

export const CLEAR_ERROR = 'CLEAR_ERROR'
