# build environment
FROM node:13.12.0-alpine as build
RUN mkdir -p /app
WORKDIR /app
ENV PATH /node_modules/.bin:$PATH
# install app dependencies
COPY package.json /app
COPY yarn.lock /app
RUN yarn

RUN yarn add react-scripts@3.4.1 -g 

# add app
COPY . /app
RUN yarn build

# production environment
FROM nginx:stable-alpine
COPY --from=build /app/build /usr/share/nginx/html
# new
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]